#!/bin/bash
python two_p_hole.py "{2:(1,), 3:(1,), 5:(1,)}" S/hf_S.tar.gz	
python two_p_hole.py "{1:(3,4,5)}" S_nosym/hf_S.tar.gz	
python two_p_hole.py "{1:(9,10,11)}" Cystein/hf_sto3g.tar.gz
python two_p_hole.py "{1:(9,10,11)}" Cystein/hf_cys.tar.gz
