#!/bin/bash
#dalton -get 'AOPROPER AO2SOINT' hf cc-pVDZ
tgz=$1
calc=$(basename $tgz .tar.gz)

ledges "{1:(3, 4, 5)}" $tgz  --output $calc.hso1
ledges "{1:(3, 4, 5)}" --two-electron $tgz  --output $calc.hso2
ledges "{1:(3, 4, 5)}" --all-electron $tgz  --output $calc.hso

width=.002 generate_spectrum.sh $calc.hso{,[12]}

split=$(python -m ledges.peaksplit 2 4 eigenvalues.hso --eV --fmt '%6.2f')
split1=$(python -m ledges.peaksplit 2 4 eigenvalues.hso1 --eV --fmt '%6.2f')
split2=$(python -m ledges.peaksplit 4 2 eigenvalues.hso2 --eV --fmt '%6.2f')

justplot2.py eigenvalues.hso{,[12]}.dat --loc "upper left" --legends "BP $split" "1el $split1" "2el $split2" --title "Argon 2p splitting"
